### ISSUE TITLE
Compatability with January update

### ISSUE THREAD

**Issue by Surfinite** [civfanatics/CQUI_Community-Edition#241]
I believe the January update broke CQUI.
I'm using an old save from before the update.
When trading with a civ, when you go to make a deal, neither sides resources show up and the game locks with no way to exit the Make A Deal screen.

I just wanted to report it, no rush or anything.  Thank you!

**Comment by ToggoStar** [comment]
Same issue here - even when starting a new game. The diplo screen works otherwise, but trading is impossible and soft-locks the game.

**Comment by Gliptal** [comment]
Just a note, if the AI offers a deal both the option to refuse and accept it still work, and get you out of the screen.

**Comment by the-m4a** [comment]
Thank you for the reports, it is much appreciated!  I believe I have fixed at least a couple of the issues and pushed that version to the workshop, as it at least makes early game playable once again.  I literally only had time to play a few turns, so I'll need to investigate further later and hopefully y'all can provide some details if you have them.

**Comment by Gliptal** [comment]
Any chance for a commit? I'm on the EGS so Steam Workshop isn't an option.

**Comment by Gliptal** [comment]
Seems to be still broken in vanilla.
![Screenshot (7)](https://user-images.githubusercontent.com/3907646/106208750-265c4e80-61c4-11eb-84c3-e7a45819a676.png)

**Comment by the-m4a** [comment]
Looking at the Vanilla stuff right now...

I'm a little bit annoyed - the CityBanners in Vanilla was broken because my code called a function called GetPopulationToolTip, which was in the Firaxis-produced CityBannerManager.lua file.  Here is that function, in its entirety, and pay attention to that first commented line above the function declaration:

```lua
-- ===========================================================================
-- Non-instance function so it can be overwritten by mods
function GetPopulationTooltip(self:CityBanner, turnsUntilGrowth:number, currentPopulation:number, foodSurplus:number)
	--- POPULATION AND GROWTH INFO ---
	local popTooltip:string = Locale.Lookup("LOC_CITY_BANNER_POPULATION") .. ": " .. currentPopulation;
	if turnsUntilGrowth > 0 then
		popTooltip = popTooltip .. "[NEWLINE]  " .. Locale.Lookup("LOC_CITY_BANNER_TURNS_GROWTH", turnsUntilGrowth);
		popTooltip = popTooltip .. "[NEWLINE]  " .. Locale.Lookup("LOC_CITY_BANNER_FOOD_SURPLUS", toPlusMinusString(foodSurplus));
	elseif turnsUntilGrowth == 0 then
		popTooltip = popTooltip .. "[NEWLINE]  " .. Locale.Lookup("LOC_CITY_BANNER_STAGNATE");
	elseif turnsUntilGrowth < 0 then
		popTooltip = popTooltip .. "[NEWLINE]  " .. Locale.Lookup("LOC_CITY_BANNER_TURNS_STARVATION", -turnsUntilGrowth);
	end
	return popTooltip;
end
```

The change that happened in the Firaxis CityBannerManager.lua was to take those few lines of code that produce that popup and move it to the point where the "UpdateStats" function called it.  They changed this little code chunk:

```lua
			if (self.m_Player == Players[localPlayerID]) then			--Only show growth data if the player is you
				local popTooltip:string = GetPopulationTooltip(self, turnsUntilGrowth, currentPopulation, total);
				self.m_Instance.CityPopulation:SetToolTipString(popTooltip);
```

to this:
```lua
			if (self.m_Player == Players[localPlayerID]) then			--Only show growth data if the player is you
				--- POPULATION AND GROWTH INFO ---
				local popTooltip:string = Locale.Lookup("LOC_CITY_BANNER_POPULATION") .. ": " .. currentPopulation;
				if turnsUntilGrowth > 0 then
					popTooltip = popTooltip .. "[NEWLINE]  " .. Locale.Lookup("LOC_CITY_BANNER_TURNS_GROWTH", turnsUntilGrowth);
					popTooltip = popTooltip .. "[NEWLINE]  " .. Locale.Lookup("LOC_CITY_BANNER_FOOD_SURPLUS", toPlusMinusString(foodSurplus));
				elseif turnsUntilGrowth == 0 then
					popTooltip = popTooltip .. "[NEWLINE]  " .. Locale.Lookup("LOC_CITY_BANNER_STAGNATE");
				elseif turnsUntilGrowth < 0 then
					popTooltip = popTooltip .. "[NEWLINE]  " .. Locale.Lookup("LOC_CITY_BANNER_TURNS_STARVATION", -turnsUntilGrowth);
				end

				self.m_Instance.CityPopulation:SetToolTipString(popTooltip);
```

As someone that does development work for a living, there's no freaking way that change gets past my review.  Literally the purpose of the prior function was to be callable by mods, and it gets removed to be in-lined into a _huge_ nearly 200-line function?  Such terribleness with their code practices.

**Comment by the-m4a** [comment]
The stuff with the diplomacy deal view is annoying in a different way:  For Expansion2, they turned the icon instance into a global object (meaning: we can access it from mod files now!)... but only for expansion2.  For exp1 and vanilla, it was still declared as local.

Anyway.  Found the issues with Vanilla and EXP1, tested both very briefly (I swear I don't seem to have time until everyone else around here is asleep) and they look good.  I pushed the update to the workshop.  I'll do the PR with those changes later on.

**Comment by Gliptal** [comment]
The only reason I can think for that change is they need to reduce function calls to support consoles like the switch.

**Comment by moiri-gamboni** [comment]
I can't load newly created internet games at all with CQUI on Ubuntu 20.04 since the update, both vanilla or either expansion. I get stuck on the leader loading screen. I didn't turn on any game modes, and all other mods were disabled. I'm not sure what log files to include so here's everything I had in my Logs folder. [Logs.zip](https://github.com/civfanatics/CQUI_Community-Edition/files/5892765/Logs.zip)

**Comment by RustyD** [comment]
> I can't load newly created internet games at all with CQUI on Ubuntu 20.04 since the update, both vanilla or either expansion. I get stuck on the leader loading screen. I didn't turn on any game modes, and all other mods were disabled. I'm not sure what log files to include so here's everything I had in my Logs folder. [Logs.zip](https://github.com/civfanatics/CQUI_Community-Edition/files/5892765/Logs.zip)

Yeah - the January Linux update might well have broken CQUI - can't load a previous game, can't start a new game   :-(

**Comment by the-m4a** [comment]
@moiri-gamboni @RustyD - I will look into the Linux tonight.  Probably something goofy with the naming of the files - I probably need to capitalize the DiplomacyDealView files, if I had to guess (as they changed the imports for that).

man, i wish they'd fix the issue where the lua.log file doesn't show up with linux!
the modding.log file doesn't really give any hints as to what's up.  (it's also another thought to myself that I want to break up the loading sections of this thing so it would be easier to determine which part of a loading section ends up broken, and easier control parts of the mod loading beforehand, etc...)

**Comment by the-m4a** [comment]
yuck.  it's the city banner files (at the very least).  the "include" stuff working differently with Linux strikes again

![image](https://user-images.githubusercontent.com/8787640/106349450-beb90880-6282-11eb-8006-abe4e1e58c19.png)

**Comment by the-m4a** [comment]
This shows it better, I suppose - I added a print statement at the start and end of each file, and before the _include("CityBannerManager_", true);_ line at the bottom of the Firaxis version of CityBannerManager.lua.  Round and round it goes, and doesn't stop until it blows the call stack up

![image](https://user-images.githubusercontent.com/8787640/106349525-59194c00-6283-11eb-9a63-d6031bf99a1c.png)

**Comment by the-m4a** [comment]
@RustyD @moiri-gamboni @alexeyOnGitHub - I pushed up a branch that _mostly_ gets Linux working.  The Banners do not appear initially, but making a change to nearly any (all?) CQUI setting will make them reappear.  For example, I would un-set and then re-set the "Show Inline City State Quests" from the CQUI General menu and they'd reappear.

This is the branch: 
https://github.com/civfanatics/CQUI_Community-Edition/tree/m4a-jan2021updatesfix-linux

There's nothing in the LiveTuner that gives me a hint as to why it requires something in CQUI be set before the banners appear, so I need to peck around or something, I don't know.

The diplomacy deal screen works-ish, I noticed the Civ names were not set correctly on the screen, but it otherwise seemed to be okay?

Either way, the difference in behavior between what Linux does and what Windows does for these file imports is just silly

**Comment by RustyD** [comment]
I've just had a quick test of your new branch - only a couple of turns for each of the standard game and both expansions, but can confirm that it works as you describe - both when starting a new game and resuming an existing game. 

It actually loads into the game, so that is improved - but without the city banners working. And then changing <anything> in the CQUI menu causes the city banners to pop up.

I've not gone further than that, so don't know about the diplomacy screen.

**Comment by RustyD** [comment]
Have just been playing a little bit more, and noticed that the city banner doesn't seem to get updated, at least with production status - no change in the turns left to complete a production nad not always changing the icon for what is actually being produced.

**Comment by Gliptal** [comment]
@RustyD I'm seeing something similar on vanilla Windows as well, see my last post in #242.

**Comment by the-m4a** [comment]
@RustyD - I figured out the issue with the banners not appearing until refresh, but that was _after_ I made a change that I'd like you to try (@moiri-gamboni @alexeyOnGitHub as well if you'd like).  I haven't had the chance to try it on Linux as my machine is being finicky right now, but I think it would work.

Same branch as before: https://github.com/civfanatics/CQUI_Community-Edition/tree/m4a-jan2021updatesfix-linux

The changes basically amount to:
- All of the logic once found in citybannermanager_CQUI_basegame.lua, citybannermanager_CQUI_expansions.lua, and citybannermanager_CQUI.lua are now simply in CityBannerManager_CQUI.lua.
- CityBannerManager_CQUI.lua is the correct casing in order to be "included" by the Firaxis CityBannerManager.lua
- All other citybannermanager_CQUI_*.lua files are commented out in the modinfo (so they do not get loaded)
- No more ReplaceUIScript entries for the CityBannerManager stuff, I am just letting the Firaxis "include" statement do it's work. 
  - for the record this makes debugging more of a pain because the error messages don't always appear in the Live Tuner

**Comment by RustyD** [comment]
I've just had a very quick play on a resumed 'standard' game, and the banners now appear to be working.

**Comment by hartmark** [comment]
I'm on linux and I had problems getting stuck on "Loading. Please wait.." and switching to the latest on m4a-jan2021updatesfix-linux branch gets everything working for me.

I'm however using a FAT32 filesystem as mod-folder to avoid the issue of files getting mixed casing.
See this post for a overview of how to make a fat-filesystem on a image file and mount it as loopback device.
https://forums.civfanatics.com/threads/tutorial-getting-mods-to-work-in-linux-most-of-the-steps-are-no-longer-needed.528742/

**Comment by moiri-gamboni** [comment]
Seems everything is working for now on this branch and I'm not using the FAT fs trick (using ext4).

**Comment by the-m4a** [comment]
@RustyD @hartmark @moiri-gamboni - thanks for the updates!  I pushed up another batch of changes - where I have attempted to finalize the changes made in this branch.   They work in Windows, and I found a couple of minor issues with the vanilla banners which are fixed.  If I can steal another bit of your time and load these changes up: if these look good then tomorrow night (probably) I'll merge these changes with the ones in my current PR and send it up to the Workshop.

**Comment by RustyD** [comment]
Another couple of turns from my standard game against your updated branch, and the basics seem to be OK (meaning that it's not a very thorough test, but nothing major appears broken).

**Comment by hartmark** [comment]
works well for me on update too

**Comment by RustyD** [comment]
Not sure if it is CQUI, Linux CQUI, Linux Civ6, or just Civ6, but the Religion lens doesn't quite appear to be working as well as I would expect (on standard game). Anyone else seen that?
