### ISSUE TITLE
Does not work easily with linux

### ISSUE THREAD

**Issue by verdra** [civfanatics/CQUI_Community-Edition#36]
**Describe the bug**
The mod does not run out of the box on linux. 
I believe this is because linux uses a case sensitive file system.

**To Reproduce**
clone repo in to "~/.local/share/aspyr-media/Sid Meier's Civilization VI/Mods/"
start game
see mod listed and enabled in "addition content" > "mods"
start game

**Expected behavior**
all the UI feature the mod provides are usable
or a script to modify the files an folders to use lowercase and alternative modinfo

**General information**
 - OS: Ubuntu 18.04
 - Version 1.0.1.104 ( I think there is a different versioning number for linux builds )
 - Expansion Gathering Storm
 - Other mods None

**Additional context**
i was able to rename the files and folder for the mod to all lower case and then change them in the modinfo file and it seems to be working now
[cqui.modinfo.txt](https://github.com/civfanatics/CQUI_Community-Edition/files/4756062/cqui.modinfo.txt)

**Comment by the-m4a** [comment]
yep, I think I learned this the hard way... @verda can you share a copy of your mods.log file from your logs folder, so we can see?
Or, which files did you rename?

**Comment by hartmark** [comment]
I'm using this to make my filesystem case-insensitive.
https://forums.civfanatics.com/threads/tutorial-getting-mods-to-work-in-linux-most-of-the-steps-are-no-longer-needed.528742/

I also make the mount permanent by adding a line similar to this to **/etc/fstab**
`/home/markus/.local/share/aspyr-media/Sid\040Meier's\040Civilization\040VI/civ6-mods.img /home/markus/.local/share/aspyr-media/Sid\040Meier's\040Civilization\040VI/Mods vfat loop,iocharset=iso8859-1,uid=markus,gid=markus,fmask=113,dmask=002 0 0`

**Comment by hartmark** [comment]
[Lua.log](https://github.com/civfanatics/CQUI_Community-Edition/files/4795551/Lua.log)
[Modding.log](https://github.com/civfanatics/CQUI_Community-Edition/files/4795553/Modding.log)
Attached logs for my game where the banners disappears.

If I do the workaround I posted above it will work as the file loading will be case-insensitive

**Comment by the-m4a** [comment]
There's  a few things in here... 1 is stuff with the ModLens, which I am guessing that perhaps the way it's loaded behaves differently on Linux?

Here's the errors in the log:
```
Runtime Error: C:\Emu\AppDataParent\Sid Meier's Civilization VI\Mods\CQUI_Community-Edition\Integrations\ML\Lenses\ModLens_Builder_Config_Default.lua:411: attempt to index a nil value
stack traceback:
	C:\Emu\AppDataParent\Sid Meier's Civilization VI\Mods\CQUI_Community-Edition\Integrations\ML\Lenses\ModLens_Builder_Config_Default.lua:411: in function '(main chunk)'
	[C]: in function 'lInclude'
	C:\Emu\AppDataParent\Sid Meier's Civilization VI\Mods\CQUI_Community-Edition\Integrations\ML\UI\minimappanel.lua:9: in function '(main chunk)'
	[C]: in function 'lInclude'
	C:\Emu\AppAssets\DLC\expansion2\UI\Replacements\MinimapPanel_Expansion1.lua:6: in function '(main chunk)'
	[C]: in function 'lInclude'
	C:\Emu\AppAssets\DLC\expansion2\UI\Replacements\MinimapPanel_Expansion2.lua:6: in function '(main chunk)'
	[C]: in function '(anonymous)'
Lua callstack:
```

Line 411 is this, and I am wagering that g_ModLenses_Builder_Config is the object that is nil
```
table.insert(g_ModLenses_Builder_Config[m_NothingColor],
```

g_ModLenses_Builder_Config is defined in ModLens_Builder.lua, which ModLens_Builder_Config_Default.lua does not directly include...

minimappanel.lua (Integrations\ML\UI) does this to include all of the ModLens_* scripts:
```
g_ModLenses = {} -- Populated by ModLens_*.lua scripts
include( "ModLens_", true )
```
I wonder if, for whatever reason, on your system it's loading ModLens_Builder_Config_Default.lua before it is loading ModLens_Builder.lua



Those ModLens filenames are camel-cased,

**Comment by the-m4a** [comment]
I think the city banners boil down to whatever the cause of this issue happens to be... which I have no idea at the moment:

```
CityBannerManager: Instance Manager built with bad Root Control [CityBanner] [Anchor]
Runtime Error: C:\Emu\AppAssets\Base\Assets\ui\instancemanager.lua:179: attempt to index a nil value
stack traceback:
	C:\Emu\AppAssets\Base\Assets\ui\instancemanager.lua:179: in function 'BuildInstance'
	C:\Emu\AppAssets\Base\Assets\ui\instancemanager.lua:36: in function 'GetInstance'
	C:\Emu\AppDataParent\Sid Meier's Civilization VI\Mods\CQUI_Community-Edition\Assets\Expansion2\CityBanners\citybannermanager.lua:540: in function 'CityBanner:Initialize'
	C:\Emu\AppDataParent\Sid Meier's Civilization VI\Mods\CQUI_Community-Edition\Assets\Expansion2\CityBanners\citybannermanager.lua:213: in function 'CityBanner:new'
	(tail call): ?
	C:\Emu\AppDataParent\Sid Meier's Civilization VI\Mods\CQUI_Community-Edition\Assets\Expansion2\CityBanners\citybannermanager.lua:2985: in function 'OnCityAddedToMap'
	[C]: in function 'func'
	[C]: in function '(anonymous)'
```

Whatever is the cause of the "bad Root Control" maybe...

or are you saying you force all of the file names to be lower case and it starts to work?

**Comment by hartmark** [comment]
The code if out of my expertise :)

But what I'm saying is that the workaround makes the file system case-insensitive. (like how Windows behaves)

Default on linux when trying to open FooBar.baz and the file is named Foobar.baz it will fail. But on windows it will open the Foobar.baz as the lookup is case-insensitive, eventhough the filesystem on windows perserves the casing in the names.

On windows you cannot have multiple files having the same name if you ignore casing, on linux it's allright as they are treated as distinct files.

**Comment by Infixo** [comment]
@ guys with Linux
Can you please describe precisely what rules should be observed to have the mod working out of the box on Linux?
What should be lowercased? I mean - directories? File names? All of them?
Is a name like abcd_CQUI allowed or should it be abcd_cqui?
Any other rules? Etc.

**Comment by hartmark** [comment]
I have no knowledge of the code but the issue on Linux is that the code has some reference to file FooBar.txt, but the file on disk is named fobar.txt

The same applies to folder names.

There's not that the names are not allowed, it's just that the names in the code need to be the same, including casing of letters. One good rule might to have everything in lowercase to avoid any confusion.

**Comment by aw-was-here** [comment]
The basic problem is that the Lua code uses one case and the files are actually written as a different case.  The problem is probably pretty easy to see on Mac OS.  

FWIW, given I run ZFS I finally worked around the issue by creating a custom ZFS file system with the case sensitivity property turned off (zfs set casesensitivity=insensitive fs).  CQUI now appears to be working just fine.  But that's probably not a viable workaround for most people.

**Comment by hartmark** [comment]
ext4 file sytem have also a flag to set it to case insensitive, but I'm on btrfs so I needed some extra magic using a loopback file and mount it as fat to make it work

**Comment by the-m4a** [comment]
If we can get another copy of a modding.log and Lua.log file, maybe can pick out what is failing to load.  I have been trying to keep eyes open for instances where the casing doesn't match - a couple of the files in  expansion1 or 2 I think still have improper casing on their include statement

**Comment by the-m4a** [comment]
@verdra @hartmark @aw-was-here - Can you give the mod another shot (without whatever modifications you've made on your own)?  I think we have all of the casing issues corrected now, so I am curious to see.  If it doesn't work, perhaps it's issues in XML file includes

**Comment by verdra** [comment]
sorry about not being responsive.

i tried the latest master and i am still getting issues especially around the citybanner and modlens
[Lua.log](https://github.com/civfanatics/CQUI_Community-Edition/files/4891481/Lua.log)
[Modding.log](https://github.com/civfanatics/CQUI_Community-Edition/files/4891483/Modding.log)

**Comment by the-m4a** [comment]
The logs are very useful, thank you!  The Lua log shows me it's something with the more lens integration.  I will look and see if it's something obvious that can be fixed -- maybe it's a matter of updating our version of it.  I was looking at the logs on my phone so I haven't yet been able to also look at the code.  Also didn't see anything in the modding.log which was surprising, but ok.

In the meantime if you wouldn't mind a quick test - can you subscribe to the MoreLenses mod and run it without CQUI to see if it works standalone?

The lens shown on the city screen is intertwined with this so for at least the time being we need to keep ML integration...

Thanks again!

**Comment by verdra** [comment]
MoreLenses causes the minimap to disappear
[Lua.log](https://github.com/civfanatics/CQUI_Community-Edition/files/4892966/Lua.log)
[Modding.log](https://github.com/civfanatics/CQUI_Community-Edition/files/4892967/Modding.log)

**Comment by the-m4a** [comment]
Looks to be similar if not same issue, thanks for the logs!

**Comment by Infixo** [comment]
I am curious: are all the files in the firaxis distribution for Linux lowercased by default? Or are the names the same as in Windows distribution? Also, if they are lowercased, then are all include statements also using lowercased names?

**Comment by verdra** [comment]
yes i believe all the files in the linux distribution are lowercased. though it looks like the a few of the folder are not. i am not sure where to check for the include statements.

**Comment by hartmark** [comment]
Sorry for late response, I'm on vacation and will be back day after tomorrow.

I see some logs have been posted. Poke me if more is needed.

**Comment by the-m4a** [comment]
@verdra @hartmark can you try the version of the mod from this branch: https://github.com/civfanatics/CQUI_Community-Edition/tree/m4a-LinuxIssues-36

The issue I'm seeing in the lua.log file looks to be caused by a load order issue.  The errors observed in the respective Lua.log files from the actual ModLenses mod and the version in CQUI are different, but similar.

```
Runtime Error: C:\Emu\AppDataParent\Sid Meier's Civilization VI\Mods\CQUI_Community-Edition\Integrations\ML\Lenses\ModLens_Builder_Config_Default.lua:411: attempt to index a nil value
stack traceback:
	C:\Emu\AppDataParent\Sid Meier's Civilization VI\Mods\CQUI_Community-Edition\Integrations\ML\Lenses\ModLens_Builder_Config_Default.lua:411: in function '(main chunk)'
	[C]: in function 'lInclude'
	C:\Emu\AppDataParent\Sid Meier's Civilization VI\Mods\CQUI_Community-Edition\Integrations\ML\UI\minimappanel.lua:9: in function '(main chunk)'
	[C]: in function 'lInclude'
	C:\Emu\AppAssets\DLC\expansion2\UI\Replacements\MinimapPanel_Expansion1.lua:6: in function '(main chunk)'
	[C]: in function 'lInclude'
	C:\Emu\AppAssets\DLC\expansion2\UI\Replacements\MinimapPanel_Expansion2.lua:6: in function '(main chunk)'
	[C]: in function '(anonymous)'
```

ModLens_Builder_Config_Default.lua is a file that is "included" by ModLens_Builder.lua.  I think it may be that issue where the "include" statement in minimappanel.lua includes ModLens_*, which may somehow cause the order to be weird.

The other possibility is LoadOrder stuff somehow behaves differently with Linux, and because the ModLens_Builder_Config_Default has a lower value, it loads earlier than the file that includes it.  So if this first attempt doesn't work, the second attempt will be to increase the value of the LoadOrder in the "MORELENSES_LENSES_BUILDER_CONFIG" to see if that makes a difference:

```

        <ImportFiles id="MORELENSES_LENSES">
            <Properties>
                <LoadOrder>10</LoadOrder>
                <Context>InGame</Context>
            </Properties>
            <Items>
                <File>Integrations/ML/Lenses/ModLens_Builder.lua</File>
                <File>Integrations/ML/Lenses/ModLens_Scout.lua</File>
                <File>Integrations/ML/Lenses/ModLens_Archaeologist.lua</File>
                <File>Integrations/ML/Lenses/ModLens_Barbarian.lua</File>
                <File>Integrations/ML/Lenses/ModLens_Naturalist.lua</File>
                <File>Integrations/ML/Lenses/ModLens_Wonder.lua</File>
                <File>Integrations/ML/Lenses/ModLens_CitizenManagement.lua</File>
            </Items>
        </ImportFiles>

        <ImportFiles id="MORELENSES_LENSES_BUILDER_CONIFG">
            <Properties>
                <LoadOrder>9</LoadOrder>
                <Context>InGame</Context>
            </Properties>
            <Items>
                <File>Integrations/ML/Lenses/LensSupport.lua</File>
                <File>Integrations/ML/Lenses/ModLens_Builder_Config_Default.lua</File>
            </Items>
        </ImportFiles>
```

**Comment by verdra** [comment]
still showing the error of missing mini-map and city banner
[Modding.log](https://github.com/civfanatics/CQUI_Community-Edition/files/4900670/Modding.log)
[Lua.log](https://github.com/civfanatics/CQUI_Community-Edition/files/4900671/Lua.log)

**Comment by the-m4a** [comment]
alrighty... attempt #2.  I saw another spot that did that "different" include statement.  Also saw that this statement:

```
Error opening/reading where=, file=C:\Emu\AppDataParent\Sid Meier's Civilization VI\Mods\CQUI_Community-Edition\Assets\Expansion1\Replacements\WorldTracker_Expansion1.lua
```

There was no <ReplaceUIScript> entry in the modinfo file... the CQUI version is lower-cased, and while the <Files> entries had the proper casing, the lack of the <ReplaceUIScript> entry meant possible issues.  

I also added a lines of print at the top of the modlenses files just to see what is loading and in what order.  This is a curious issue, for sure, and I wish I could reproduce it locally somehow

**Comment by verdra** [comment]
here is what i currently running, i think i deleted the city banner stuff but i got the minimap and lenses working

https://github.com/verdra/CQUI_Community-Edition/tree/my_branch
[Modding.log](https://github.com/civfanatics/CQUI_Community-Edition/files/4901236/Modding.log)
[Lua.log](https://github.com/civfanatics/CQUI_Community-Edition/files/4901237/Lua.log)

**Comment by the-m4a** [comment]
weird.  there's still errors in there, maybe these errors are benign?  very strange.

```
StatusMessagePanel: INITIALZE: CQUICommon.lua
Error opening/reading where=, file=C:\Emu\AppDataParent\Sid Meier's Civilization VI\Mods\CQUI_Community-Edition\assets\expansion1\replacements\WorldTracker_Expansion1.lua
MapSearchPanel: Created SearchContext 'MapSearch_Primary'
MapSearchPanel: Created SearchContext 'MapSearch_Suggestions'
MinimapPanel: INITIALZE: CQUICommon.lua
MinimapPanel: INITIALZE: CQUICommon.lua
MinimapPanel: Governor Builder Index = 4
MinimapPanel: Governor Builder Aquaculture hash = -122625491
MinimapPanel: Governor Builder Parks Rec hash = 1630405030
Runtime Error: C:\Emu\AppDataParent\Sid Meier's Civilization VI\Mods\CQUI_Community-Edition\integrations\ml\lenses\modlens_builder_config_default.lua:411: attempt to index a nil value
stack traceback:
	C:\Emu\AppDataParent\Sid Meier's Civilization VI\Mods\CQUI_Community-Edition\integrations\ml\lenses\modlens_builder_config_default.lua:411: in function '(main chunk)'
	[C]: in function 'lInclude'
	C:\Emu\AppDataParent\Sid Meier's Civilization VI\Mods\CQUI_Community-Edition\integrations\ml\ui\minimappanel.lua:9: in function '(main chunk)'
	[C]: in function 'lInclude'
	C:\Emu\AppAssets\DLC\expansion2\UI\Replacements\MinimapPanel_Expansion1.lua:6: in function '(main chunk)'
	[C]: in function 'lInclude'
	C:\Emu\AppAssets\DLC\expansion2\UI\Replacements\MinimapPanel_Expansion2.lua:6: in function '(main chunk)'
	[C]: in function '(anonymous)'
Lua callstack:

@C:\Emu\AppDataParent\Sid Meier's Civilization VI\Mods\CQUI_Community-Edition\integrations\ml\ui\minimappanel.lua:9
@C:\Emu\AppAssets\DLC\expansion2\UI\Replacements\MinimapPanel_Expansion1.lua:6
@C:\Emu\AppAssets\DLC\expansion2\UI\Replacements\MinimapPanel_Expansion2.lua:6
Error loading file where=C:\Emu\AppDataParent\Sid Meier's Civilization VI\Mods\CQUI_Community-Edition\integrations\ml\ui\minimappanel.lua:9: , file=C:\Emu\AppDataParent\Sid Meier's Civilization VI\Mods\CQUI_Community-Edition\integrations\ml\lenses\modlens_builder_config_default.lua
MinimapPanel: INITIALZE: CQUICommon.lua
```

**Comment by the-m4a** [comment]
@verdra did you get the chance to run the more recent update to the branch?  it'd give me a better idea of what's happening based on the logging I added

thanks!

**Comment by verdra** [comment]
just did. heres what i got.
[Modding.log](https://github.com/civfanatics/CQUI_Community-Edition/files/4907919/Modding.log)
[Lua.log](https://github.com/civfanatics/CQUI_Community-Edition/files/4907920/Lua.log)

**Comment by Infixo** [comment]
1. The problem is visible in the first set of lua callstack - it contains original files from the game.
ML overwrites original files and they should NEVER appear in the log.
2. It originates most likely from the 2 naming standards that you introduced to .modinfo. Some files in ML are lowercased, and some are capitalized. Basically the game runs 2 different copies of minimappanel.lua and they conflict ofc.
3. How to solve it. I asked a few posts above about the naming of the original files and didn’t get answer but you need to check that. Then either a) name the files in ML exactly the same or b) make sure that files used in ML have consistent naming and add proper ReplaceUI that points to those file. When you check how minimappanel.lua and .xml are precisely named, then it will be easier to decide what names should be used in CQUI.

**Comment by the-m4a** [comment]
I noticed the expansion1 and expansion2 of minimappanel._xml_ are lowercased in the actual MoreLenses mod, so I made that change.  I added a print line to the top of worldtracker_expansion1.lua as well, because that "failed to import" stuff is weird, and I am curious about that as well.  If you wouldn't mind giving it another shot...

There _might_ be issues going on if you have already done some renaming of files -- for example, this stack makes me wonder because of the casing -- not sure if Linux has already forced the all-lower-case with the base files (as we can see in other stacks that the expansion1/expansion2 directories are _not_ lowercased)...
that said, it _does_ find the files, so maybe that's just something we're seeing in the logs:

stack traceback:
	C:\Emu\AppAssets\Base\Assets\**ui\instancemanager.lua:179:** in function 'BuildInstance'
	C:\Emu\AppAssets\Base\Assets\**ui\instancemanager.lua:36:** in function 'GetInstance'
	C:\Emu\AppDataParent\Sid Meier's Civilization VI\Mods\CQUI_Community-Edition\Integrations\ML\UI\minimappanel.lua:181: in function 'CreateMapOptionButton'
	C:\Emu\AppAssets\DLC\**expansion2**\UI\Replacements\MinimapPanel_Expansion2.lua:56: in function 'CreateMapLabelToggle'
	C:\Emu\AppAssets\DLC\**expansion2**\UI\Replacements\MinimapPanel_Expansion2.lua:132: in function 'LateInitialize'
	C:\Emu\AppDataParent\Sid Meier's Civilization VI\Mods\CQUI_Community-Edition\Integrations\ML\UI\minimappanel.lua:1551: in function 'OnInit'
Lua callstack:



FWIW it doesn't look like ML overwrites those two files - MinimapPanel_Expansion1 and 2, maybe it should.  It then correctly goes to the minimappanel.lua found in the standard folder:
```
stack traceback:
	C:\Emu\AppDataParent\Sid Meier's Civilization VI\Mods\CQUI_Community-Edition\Integrations\ML\UI\minimappanel.lua:1568: in function 'Initialize'
	C:\Emu\AppDataParent\Sid Meier's Civilization VI\Mods\CQUI_Community-Edition\Integrations\ML\UI\minimappanel.lua:1610: in function '(main chunk)'
	[C]: in function 'lInclude'
	C:\Emu\AppAssets\DLC\expansion2\UI\Replacements\MinimapPanel_Expansion1.lua:6: in function '(main chunk)'
	[C]: in function 'lInclude'
	C:\Emu\AppAssets\DLC\expansion2\UI\Replacements\MinimapPanel_Expansion2.lua:6: in function '(main chunk)'
	[C]: in function '(anonymous)'
```

**Comment by Infixo** [comment]
ML works on Windows. It means that making it work on Linux is a matter of proper naming and load order. Unless you wanna do random changes and hope for some luck to make it work, I'd rather wait for Linux guys to tell the exact naming of the related files on Linux. That should help to name them properly in the mod.

**Comment by the-m4a** [comment]
@verdra any chance you've tried the most recent again?  curious of the result if so
thanks!

**Comment by chaorace** [comment]
FYI, all files on the Asypr port are lowercased. For the sake of convenience (and posterity), I've dumped the file trees for the base and expansion files in [this gist](https://gist.github.com/chaorace/1c699534c1a9a8e6559a288c059e102f).

**Comment by RustyD** [comment]
@the-m4a Is there any branch that I can test running in Linux to give you some feedback? I've tried the 'm4a-LinuxIssues-36' branch, and that has a visible mini map in standard and both (first 2) extensions. But the city banner is still missing when running a game with either of the expansions (standard game seems ok). 
Also, where do I find the Lua.log file to check for other errors, as I can't seem to find it on my system?

**Comment by Infixo** [comment]
@RustyD I don't know if @the-m4a 's branch is valid any more. Maybe just try the master and post all logs here (zip pls).
I don't know where logs are on Linux. On Windows they are in [user]\Documents\My Games\Sid Meier's Civilization VI\Logs. Mods and Logs reside side by side. Logs: database, modding and lua.

**Comment by RustyD** [comment]
@Infixo Yeah - I can see a lot of other logs in the Log directory (FYI - ~/.local/share/aspyr-media/Sid Meier's Civilization VI/Logs), but NOT the Lua.log file. 
I was also skimming over the commit history to see if anything stood out regarding fixing the city banner, but no luck. I'll look at trying a more recent branch.

**Comment by RustyD** [comment]
I just creating a new GS game with CQUI mod branch "m4a-techcivicpopuptake2-171" active (a few commits on from master) and had no minimap and no city banner after I built my city.
Logs attached.
[civ6-logs.zip](https://github.com/civfanatics/CQUI_Community-Edition/files/5204214/civ6-logs.zip)

**Comment by Infixo** [comment]
> @Infixo Yeah - I can see a lot of other logs in the Log directory (FYI - ~/.local/share/aspyr-media/Sid Meier's Civilization VI/Logs), but NOT the Lua.log file.

Lua.log is actuallu THE log that is needed the most. Weird that you don't have it.

**Comment by Infixo** [comment]
Anyway, check your game installation because you have DB errors from the game core.

[2037872.888] [Gameplay] ERROR: table Colors already exists
[2037872.888] [Gameplay]: In XMLSerializer while building table Colors from file color_tables.xml.
[2037872.888] [Gameplay] ERROR: table DiplomacyStatements already exists
[2037872.888] [Gameplay]: In XMLSerializer while building table DiplomacyStatements from file diplomacy_tables.xml.
[2037872.888] [Gameplay] ERROR: table LeaderAnimations already exists
[2037872.888] [Gameplay]: In XMLSerializer while building table LeaderAnimations from file leader_tables.xml.

**Comment by aw-was-here** [comment]
>  ~/.local/share/aspyr-media/Sid Meier's Civilization VI/Logs), but NOT the Lua.log file.

FWIW, in my last run in July, this is where my Lua.log file is at.

**Comment by RustyD** [comment]
I'll check my installation.
But I've just managed to get the minimap to appear in a new GS game, after I rebased the "m4a-LinuxIssues-36" branch on top of master, renamed to linux-issues-36
But I don't have permission to push that, so can't share for the moment.
No city banner though.

**Comment by RustyD** [comment]
Well, I uninstalled Civ6 (via Steam) and deleted my '.local' files and then re-installed with just the 2 expansion mods. I still get the same errors in 'Database.log' (all 3 duplicated), so I'm not sure that it should be a problem?

I still don't seem to have a 'Lua.log' file in the 'Logs' folder.

And, rather stupidly, I deleted the cloned CQUI git repo that contained my rebased branch. Doh!

Maybe I'll fork this repo and try pushing my changes to that.

**Comment by the-m4a** [comment]
@RustyD - Yeah, that branch likely isn't valid at the moment... I had planned to start with going with proper casing for all files in CQUI (basically undoing all of the lower-casing from a few months back) and starting to pick things up from there.  If I get time tonight I'll create a new branch and whatnot... 
Like Infixo said tho, finding that Lua.log, Modding.log, and UserInterface.log files would be super helpful!

**Comment by the-m4a** [comment]
@RustyD - would you mind verifying if the Minimap/Lenses work from the branch m4a-morelensesupdate?  I just went through and pulled all of the recent changes from MoreLenses over, except for changes in casing (the "real" ML mod lower-cased all file refrences...but as best I can tell did not actually lowercase the file names).

**Comment by RustyD** [comment]
@the-m4a I've just quickly tried this out (using a R&F game that I have been playing using my branch from yesterday, where the minimap **was** visible). 

Using your m4a-morelensesupdate branch, I **couldn't** see any minmap. 

So I then tried creating a new game using the standard rules, and the minimap **wasn't** visible there either.

:-(

**Comment by StragaSevera** [comment]
I have the same problem - both the minimap and the cities banners were abscent. I'm using ArchLinux, and this is my Logs folder content (no Lua.log either):
https://drive.google.com/file/d/1x0LKo04v3J3vE0DTZL-YrxgP9pfM2qzJ/view?usp=sharing

**Comment by Infixo** [comment]
Guys, maybe there is simply a bug and Lua.log is no longer generated in Linux installations. Maybe this should be reported oficially to Firaxis/Aspyr.
Can anyone confirm that he/she is getting the log on Linux?

**Comment by the-m4a** [comment]
Is the SDK - or more specifically, the Fire Tuner - something that can be run in the Linux environment?  The lack of Lua logs is odd though.  Where do such things get officially reported?

**Comment by RustyD** [comment]
I fired up my old desktop but that had some issues running Steam. It had run Civ6 in the past, because there were all the relevant logs files, etc present. Including the **lua.log** file! It's contents would not have been relevant though.

But, in order to test your changes I needed to get Steam working. Long story short, I spent 5 or so hours upgrading from Mint 19.3 to Mint 20 and re-installing a lot of stuff - including Steam.

Now with a working Steam I was able to test CQUI. Unfortunately however, I experienced the same results as on my other machine - including no **lua.log** file.  :-(

So maybe this a Mint Linux (based on Ubuntu) or a wider Linux issue with no **lua.log** file. Maybe this _should_ be report to Firaxis/Aspyr?

**Comment by RustyD** [comment]
> Is the SDK - or more specifically, the Fire Tuner - something that can be run in the Linux environment? The lack of Lua logs is odd though. Where do such things get officially reported?

I have no idea about the SDK or Fire Tuner. Any pointers?

**Comment by hartmark** [comment]
There's a Civilization channel on Aspyr's discord where some developers peek into, you can also get responses from other knowledgeable people there and if you get no response you can lodge a ticket in their bug-tracker.
discord.gg/AspyrMedia

**Comment by RustyD** [comment]
I've gone to that discord channel and raised the question. Hopefully someone might have a answer, but probably best not to hold your breath.

**Comment by RustyD** [comment]
I've created a new pull request #189 that is branch off of the 'more lenses' branch by @the-m4a .

Without the Lua.log file available, I'm pretty stuck not being able to highlight specific errors with the Minimap and City Banners not working, but I still thought I'd spend some time manually investigating and trying out various fix 'guesses'.

I've managed to get the minimap working, but the city banners still remain an issue in the expansions.

I don't know if you do/don't want to accept my pull request, but it at least means there will be one less 'critical' issue using CQUI on Linux if you do accept it.

**Comment by the-m4a** [comment]
Any chance the Lua.log file has made a reappearance with today's update from Firaxis?

**Comment by the-m4a** [comment]
Also - started up a game with Gaul, running just CQUI and the "better civ colors" mod (which is just XML changes away from ours).  So far, things look ok.

**Comment by RustyD** [comment]
> Any chance the Lua.log file has made a reappearance with today's update from Firaxis?

I've just had a quick check, and no **Lua.log** for me  :(

**Comment by the-m4a** [comment]
darn, wonder what's up with that

**Comment by the-m4a** [comment]
@RustyD If you haven't already, can you open up the AppOptions.txt (under .local/share/aspyr-media/Sid Meier's Civilization VI and set EnableTuner to 1 (for the FireTuner)?  Maybe that'll cause the lua log to start showing up as well.

I have been trying on and off for the past couple of weeks to get Linux running in the Windows Subsystem for Linux environment; I managed to get Steam installed and have it download Civ, but haven't yet succeeded in getting Civ 6 to actually launch.  Steam has some sort of issue where it literally works once - when I first install it - subsequent times there's this weird error and I can't get it to launch again unless I remove the ~/.steam folder

I *can* get SteamCmd to run, but I can't get it to launch Civ (it givesme something about invalid configuration).  As a relative newbie to Linux... I have no idea why y'all like it. :smile:

**Comment by RustyD** [comment]
@the-m4a Yeah - I've had that 'EnableTuner' set to 1 for a while now, and still no lua log.

I think I'm resigning myself to the fact that Aspyr and Fireaxis don't really care that much about their Mac and Linux ports, given their responsiveness on the issues that we see. I think Fireaxis will need to make Civ7 multiplatform by default (and not rely on the porting services of a third party) in order for me to take an 'early' risk on buying that when it makes an appearance.

I'll admit that using Linux can be frustrating at times, but for me I converted over from Windows after Win8 came out. Did not like that interface at all. And, I didn't like a lot of what Microsoft was doing with Windows in general. One of the things keeping me on Windows back then was MS Office, but around that time LibreOffice became good enough for my needs. Other than that, (and being a coder all my life), I also prefer the philosophy of open source code. I think the world would be a 'better' place if propriety software had a lot smaller role (I'm not saying _all_ software has to be open source, but if I find a bug I have a chance to contribute to fixing it, which I have done in the past - a bit like this mod!). 

I'm not sure how ready Windows Subsystem for Linux is for those demands and expectations that you're placing on it!  :-)

**Comment by the-m4a** [comment]
Hah my only demand is to get me into Civ, it doesn't have to look pretty.  I just don't know enough to know if I can get there or not... I got to the point where I saw the intro screen, but I think once I get somewhere that requires DirectX 11... it goes boom and just shows me a white screen. :/

**Comment by the-m4a** [comment]
I wonder if there's a way to use telnet to pretend to be the FireTuner?

**Comment by RustyD** [comment]
@the-m4a I'm not familiar with FireTuner - do you have any links?

**Comment by the-m4a** [comment]
FireTuner is part of the “Sid Meier’s Civilization VI Development Tools” item from Steam, which includes the FireTuner and Steam Workshop uploader and the like (see https://steamdb.info/app/404350/ )… which apparently does not have a Linux version. :/

Anwyay, the FireTuner is just a front end for interacting with the Game engine in some fashion – the console part of the FireTuner shows the same information that we’d get out of the Lua.log file, which is why I was curious about it.  The connection to Civ VI that the FireTuner makes is via TCP – port 4318 – which made me curious if *If* there’s a way to use telnet to behave like the console.  If I get the chance tonight or in the next few days I’ll fire up wireshark and see if I am able to capture loopback traffic and see what the FireTuner does when it makes that connection.

I also forget – did we take a look at the UserInterface.log file?  (I’m responding from email instead of on the GitHub site, so I don’t’ have access to history at the moment)


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by RustyD** [comment]
I'm not seeing anything useful in the UserInterface.log file. I've previously tried searching all the log files for some helpful errors, but with no luck.
...
[UserInterface.log](https://github.com/civfanatics/CQUI_Community-Edition/files/5369878/UserInterface.log)
